# Generated by Django 6.1 on 2026-09-02 06:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('subheading', 1), ('paragraph', 2), ('bullet_list', 4), ('numbered_list', 4), ('image', 5), ('quote', 6), ('code', 7), ('divider', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a heading', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a subheading', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Add paragraph content', 'required': True}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.BlockQuoteBlock', (), {}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add your code here', 'rows': 10}), 8: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Horizontal divider'})}),
        ),
    ]
