# Generated by Django 6.1 on 2026-09-02 07:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('subheading', 3), ('paragraph', 4), ('bullet_list', 6), ('numbered_list', 6), ('image', 7), ('quote', 8), ('code', 9), ('divider', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1 (H1)'), ('h2', 'Heading 2 (H2)'), ('h3', 'Heading 3 (H3)'), ('h4', 'Heading 4 (H4)'), ('h5', 'Heading 5 (H5)'), ('h6', 'Heading 6 (H6)')], 'help_text': 'Select heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a subheading', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'link', 'ol', 'ul', 'hr'], 'help_text': 'Add paragraph content', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Add your code here', 'rows': 10}), 10: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Horizontal divider'})}),
        ),
    ]
