# Generated by Django 6.1 on 2026-09-02 10:34

import json
import wagtail.fields
from django.db import migrations


def clean_body_json(apps, schema_editor):
    db_connection = schema_editor.connection
    with db_connection.cursor() as cursor:
        cursor.execute("SELECT page_ptr_id, body FROM blog_blogpage;")
        rows = cursor.fetchall()
        for page_id, body_val in rows:
            is_valid_json = False
            if body_val:
                try:
                    parsed = json.loads(body_val)
                    if isinstance(parsed, list):
                        is_valid_json = True
                except Exception:
                    pass

            if not is_valid_json:
                if body_val and isinstance(body_val, str) and body_val.strip() and not body_val.startswith('['):
                    stream_data = json.dumps([{"type": "paragraph", "value": body_val, "id": "migration-initial"}])
                else:
                    stream_data = "[]"

                cursor.execute("UPDATE blog_blogpage SET body = %s WHERE page_ptr_id = %s;", [stream_data, page_id])


def reverse_clean(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_body'),
    ]

    operations = [
        migrations.RunPython(clean_body_json, reverse_clean),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('subheading', 3), ('paragraph', 4), ('table', 5), ('bullet_list', 7), ('numbered_list', 8), ('image', 9), ('embed', 10), ('quote', 11), ('code', 14), ('callout', 18), ('divider', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1 (H1)'), ('h2', 'Heading 2 (H2)'), ('h3', 'Heading 3 (H3)'), ('h4', 'Heading 4 (H4)'), ('h5', 'Heading 5 (H5)'), ('h6', 'Heading 6 (H6)')], 'help_text': 'Select heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a subheading', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'code', 'link', 'document-link', 'ol', 'ul', 'blockquote', 'hr', 'image', 'embed'], 'help_text': 'Add paragraph content', 'required': True}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'help_text': 'Create a structured data table'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'List item text'}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul', 'label': 'Bullet List'}), 8: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ol', 'label': 'Numbered List'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image'}), 10: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed YouTube, Vimeo, Twitter/X, or other media URLs'}), 11: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Add a blockquote text'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('bash', 'Bash / Shell'), ('sql', 'SQL')], 'help_text': 'Select programming language for syntax highlighting'}), 13: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste your code snippet here', 'required': True, 'rows': 10}), 14: ('wagtail.blocks.StructBlock', [[('language', 12), ('code', 13)]], {}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger / Error (Red)')], 'help_text': 'Select callout alert style'}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Callout Title (Optional)', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Callout Content', 'required': True}), 18: ('wagtail.blocks.StructBlock', [[('style', 15), ('title', 16), ('text', 17)]], {}), 19: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Horizontal divider'})}),
        ),
    ]
