# Generated by Django 6.1 on 2026-09-09 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Custom canonical URL if different from current post URL'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='Primary keyword/phrase for search engines', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='is_cornerstone',
            field=models.BooleanField(default=False, help_text='Mark if this is one of your most important, comprehensive articles'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='keyphrase_synonyms',
            field=models.CharField(blank=True, help_text='Comma-separated synonyms or LSI keywords', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='robots_follow',
            field=models.BooleanField(default=True, help_text='Allow search engines to follow links in this article'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='robots_index',
            field=models.BooleanField(default=True, help_text='Allow search engines to index this article'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_image',
            field=models.ForeignKey(blank=True, help_text='Custom image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing (OG / Twitter)', max_length=255),
        ),
    ]
