# Generated by Django 6.1 on 2026-09-09 12:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpage_canonical_url_blogpage_focus_keyphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='custom_meta_description',
            field=models.TextField(blank=True, help_text='Custom SEO Meta Description (defaults to short description if blank)', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='custom_meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Title (defaults to page title if blank)', max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('subheading', 3), ('paragraph', 4), ('table', 5), ('bullet_list', 7), ('numbered_list', 8), ('image', 12), ('embed', 13), ('quote', 14), ('code', 17), ('callout', 21), ('divider', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter heading text', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h1', 'Heading 1 (H1)'), ('h2', 'Heading 2 (H2)'), ('h3', 'Heading 3 (H3)'), ('h4', 'Heading 4 (H4)'), ('h5', 'Heading 5 (H5)'), ('h6', 'Heading 6 (H6)')], 'help_text': 'Select heading level'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add a subheading', 'required': True}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'bold', 'italic', 'strikethrough', 'superscript', 'subscript', 'code', 'link', 'document-link', 'ol', 'ul', 'blockquote', 'hr', 'image', 'embed'], 'help_text': 'Add paragraph content', 'required': True}), 5: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'help_text': 'Create a structured data table'}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'List item text'}), 7: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ul', 'label': 'Bullet List'}), 8: ('wagtail.blocks.ListBlock', (6,), {'icon': 'list-ol', 'label': 'Numbered List'}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload or select an image', 'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alt text for SEO & Accessibility (Optional, defaults to image title if blank)', 'required': False}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Image caption shown below image (Optional)', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 9), ('alt_text', 10), ('caption', 11)]], {}), 13: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Embed YouTube, Vimeo, Twitter/X, or other media URLs'}), 14: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'Add a blockquote text'}), 15: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('bash', 'Bash / Shell'), ('sql', 'SQL')], 'help_text': 'Select programming language for syntax highlighting'}), 16: ('wagtail.blocks.TextBlock', (), {'help_text': 'Paste your code snippet here', 'required': True, 'rows': 10}), 17: ('wagtail.blocks.StructBlock', [[('language', 15), ('code', 16)]], {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)'), ('danger', 'Danger / Error (Red)')], 'help_text': 'Select callout alert style'}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Callout Title (Optional)', 'required': False}), 20: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Callout Content', 'required': True}), 21: ('wagtail.blocks.StructBlock', [[('style', 18), ('title', 19), ('text', 20)]], {}), 22: ('wagtail.blocks.static_block.StaticBlock', (), {'admin_text': 'Horizontal divider'})}),
        ),
    ]
