# Generated by Django 6.1 on 2026-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpage_custom_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for featured image (defaults to image title if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='social_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for social share image (defaults to image title if blank)', max_length=255),
        ),
    ]
