# Generated by Django 6.1 on 2026-09-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='featured_image_alt',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='social_image_alt',
        ),
    ]
