# Generated by Django 6.1 on 2026-09-10 05:16

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpage_featured_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.CharField(default=blog.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BlogSubCategory',
            fields=[
                ('id', models.CharField(default=blog.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Sub Category',
                'verbose_name_plural': 'Blog Sub Categories',
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.blogsubcategory'),
        ),
    ]
