# Generated by Django 6.1 on 2026-09-10 06:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogcategory_id_blogsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Category description'),
        ),
    ]
