# Generated by Django 6.1 on 2026-09-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcomment_bloglike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description'),
        ),
    ]
