# Generated by Django 6.1 on 2026-09-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
