# Generated by Django 6.1 on 2026-09-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_create_uncategorized_category_and_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='Primary keyword/phrase for search engines', max_length=100),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Description (defaults to page description if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Title (defaults to page title if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Title (defaults to page title if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogsubcategory',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='Primary keyword/phrase for search engines', max_length=100),
        ),
        migrations.AddField(
            model_name='blogsubcategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Description (defaults to page description if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogsubcategory',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Title (defaults to page title if blank)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogsubcategory',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Custom SEO Meta Title (defaults to page title if blank)', max_length=255),
        ),
    ]
