# Generated by Django 6.1 on 2026-09-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogcategory_focus_keyphrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='blogsubcategory',
            name='meta_title',
        ),
    ]
