# Generated by Django 6.1 on 2026-09-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blogcategory_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsubcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Category description'),
        ),
    ]
